export { default as App } from "./App";
export { default as SingleProduct } from "./SingleProduct";
export { default as AllProducts } from "./AllProducts";
export { default as NavBar } from "./NavBar";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Profile } from "./Profile";
export { default as SingleOrder } from "./SingleOrder";
export { default as Cart } from "./Cart";
